export const streamPrimaryMedia = Object.freeze({
  "born-of-burn": { path: "img/born_of_burn/3.webp", width: 360, height: 450 },
  "by-marks-and-fire": { path: "img/by_marks_and_fire/3.webp", width: 768, height: 1024 },
  "christmas-joy": { path: "img/christmass_joy/1.jpeg", width: 360, height: 450 },
  core: { path: "img/core/2.webp", width: 360, height: 450 },
  full: { path: "img/full/full.jpeg", width: 1586, height: 1982 },
  "july-pines": { path: "img/july_pines/4.jpeg", width: 3200, height: 4000 },
  moonglow: { path: "img/moonglow/1.webp", width: 360, height: 450 },
  "navy-of-the-dreamland": { path: "img/navy_of_the_dreamland/navy.webp", width: 789, height: 996 },
  "of-ash-and-flowers": { path: "img/of_ash_and_flowers/of_ash.webp", width: 360, height: 548 },
  prolisok: { path: "img/prolisok/1.webp", width: 360, height: 450 },
  "rise-in-blue": { path: "img/rise_in_blue/2.webp", width: 1584, height: 1982 },
  spectral: { path: "img/spectral/2.webp", width: 360, height: 450 },
  whales: { path: "img/whales/whale.webp", width: 500, height: 360 },
  winds: { path: "img/winds/winds.webp", width: 800, height: 1001 },
  "spring-fire": { path: "img/spring_fire/4.jpeg", width: 793, height: 990 },
  "mermaid-s-dream": { path: "img/mermaids_dream/4.jpeg", width: 768, height: 1024 },
  "golden-monstera": { path: "img/golden_monstera/1.jpeg", width: 1022, height: 1280 },
  "fragments-of-light": { path: "img/fragments_of_light/5.jpeg", width: 1536, height: 2048 },
  "november-forest": {
    path: "img/november_forest/EEDFEC9D-738E-4534-BCA2-33C772BC0AB6_4_5005_c.jpeg",
    width: 360,
    height: 480,
  },
  "their-shore": { path: "img/their_shore/2.jpeg", width: 962, height: 817 },
  "the-place-that-stays": { path: "img/the_place_that_stays/the_place.jpeg", width: 994, height: 790 },
  compass: { path: "img/following_her_steps/iris_1/2.jpeg", width: 1788, height: 1756 },
  choice: { path: "img/following_her_steps/iris_2/1.jpeg", width: 1784, height: 1760 },
  return: { path: "img/following_her_steps/iris_3/1.jpeg", width: 1786, height: 1760 },
  light: { path: "img/following_her_steps/iris_4/light.jpeg", width: 1772, height: 1774 },
  dreaming: { path: "img/following_her_steps/iris_5/1.jpeg", width: 1790, height: 1754 },
  grounded: { path: "img/following_her_steps/iris_6/grounded.jpeg", width: 1762, height: 1784 },
  after: { path: "img/following_her_steps/iris_7/3.jpeg", width: 1786, height: 1760 },
  release: { path: "img/following_her_steps/iris_8/2.jpeg", width: 1790, height: 1754 },
  clarity: { path: "img/following_her_steps/iris_9/3.jpeg", width: 1772, height: 1774 },
  "texas-storm": { path: "img/texas_storm/2.jpeg", width: 1586, height: 1982 },
  magnet: { path: "img/magnet/3.jpeg", width: 1531, height: 2054 },
});

export const streamPrimaryPaths = Object.freeze(Object.fromEntries(
  Object.entries(streamPrimaryMedia).map(([id, media]) => [id, media.path]),
));
